### ISSUE TITLE
Pollard.hs

### ISSUE THREAD

**Issue by cornservant** [FG-TUM/Computer-Algebra#2]
In den Zeilen

https://github.com/FG-TUM/Computer-Algebra/blob/master/Sheet6/Exercise3_Pollard.hs#L12
https://github.com/FG-TUM/Computer-Algebra/blob/master/Sheet6/Exercise3_Pollard.hs#L18

sollte jeweils das lezte Argument von pollardAux modulo n reduziert werden

**Comment by FG-TUM** [comment]
Hmm das erklärt wo die memory overflows her kamen :D Thx!
